/* CREATING DATABASE */

CREATE DATABASE NETFLIX

/* CREATING TABLE */

DROP TABLE IF EXISTS OTT
CREATE TABLE OTT
  (
        SHOW_ID VARCHAR(6),
		TYPE VARCHAR(10) ,
		TITLE VARCHAR(150),
		DIRECTOR VARCHAR(208),
		CASTS VARCHAR(1000),
		COUNTRY VARCHAR(150),
		DATE_ADDED VARCHAR(50),
		RELEASE_YEAR INT,
		RATING VARCHAR(10),
		DURATION VARCHAR(15),
		LISTED_IN VARCHAR(100),
		DESCRIPTION VARCHAR(250)
  )

 SELECT * FROM OTT

 SELECT COUNT(*) AS TOTAL_COUNT FROM OTT

 SELECT DISTINCT TYPE FROM OTT

 
